import "@/styles/globals.scss";

import { AppProps } from "next/app";
import Head from "next/head";

import { CustomCursor } from "@/components/common";

import { ParallaxProvider } from "react-scroll-parallax";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Pourya Nofallah | Personal Website</title>
        <meta name="description" content="Generated by pourya nofallah" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-gray-900 ">
        <CustomCursor />
        <main className="flex flex-col justify-center items-center">
          <ParallaxProvider>
            <Component {...pageProps} />
          </ParallaxProvider>
        </main>
      </div>
    </>
  );
}
